### PR TITLE
White on black option and escaping '<'

### PR DESCRIPTION
**Pull request by bobes**
- added '--black' argument that reverts color and background color
- escaping '<' so it is displayed properly in html

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thank for your patch. I'm no longer maintaining this library, because I found a better one:

http://rtomayko.github.com/bcat/
http://rtomayko.github.com/bcat/a2h.1.html

Aslak

**Comment by bobes** [comment]
bcat looks great but it doesn't seem to escape '<' character either and I haven't found a way to make the background black

**Comment by bobes** [comment]
actually, bcat does escape <, but a2h does not

**Comment by aslakhellesoy** [comment]
Ha! Maybe I'll keep this thing alive a little longer then :-)

**Comment by aslakhellesoy** [comment]
5.3.4 released with your changes!

**Pull request merged**
